# -*- coding: utf-8 -*-
"""Memristor_Verilog_Python_Superimposed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5viQlbWxoP4GNLVpWDVehQPRK7DPIWD
"""

# =================================================================
# PART 1: Physical Parameters & Mathematical Model
# =================================================================
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files

k_B, T, G0, L = 8.617e-5, 300, 0.4e-5, 0.7e-9
beta, k_attempt = 0.59e-9, 1e10
Is, n_set, n_reset, vt = 1.0e-10, 29, 21, 0.026
G_metallic = 0.4e-5
freq, V_max = 1e3, 4.0
t = np.linspace(0, 1/freq, 25000)
V_signal = V_max * np.sin(2 * np.pi * freq * t)
dt = t[1] - t[0]

class MoTe2:
    def __init__(self):
        self.v_off, self.v_on = 0.2, -0.2
        self.Eset, self.Ereset = 3.7, 3.3
        self.w = 0
        self.p_set, self.p_reset = 2.0, 0.8
    def dw_dt(self, v):
        if v > self.v_off:
            return k_attempt * np.exp((-(self.Eset - beta * (v/L)) / (k_B * T))) * (1 - self.w)**self.p_set
        elif v < self.v_on:
            return k_attempt * np.exp((-(self.Ereset - beta * (abs(v/L))) / (k_B * T))) * -(self.w**self.p_reset)
        return 0

memristor = MoTe2()
current = []
for v in V_signal:
    dw_val = memristor.dw_dt(v)
    memristor.w = np.clip(memristor.w + dw_val * dt, 0, 1)
    n_curr = n_set if v >= 0 else n_reset
    I_sch = Is * (np.exp(np.abs(v) / (n_curr * vt)) - 1) * np.sign(v)
    I_met = G_metallic * v
    current.append(np.maximum(np.abs((1 - memristor.w) * I_sch + memristor.w * I_met), 1e-13))

# =================================================================
# PART 2: Base Plotting & Reference Data
# =================================================================
plt.figure(figsize=(10, 6))

# Styled to match exactly: thicker blue line
plt.semilogy(V_signal, current, label="Python Mathematical Model", color='tab:blue', linewidth=2.5)

x_exp = [0.05913, 0.11386, 0.14123, 0.19386, 0.4107, 0.817, 1.16857, 1.57488, 2.06118, 2.49485, 2.90116, 3.30746, 3.65903, 3.82113, 4.03797, 3.87587, 3.63166, 3.38956, 3.01063, 2.71169, 2.44012, 2.14328, 1.81908, 1.52014, 1.1412, 0.84437, 0.54543, 0.30333, 0.14123, 0.03176, 0.00439, -0.02298, -0.04824, -0.10297, -0.18508, -0.29244, -0.53665, -0.94295, -1.51136, -2.10713, -2.79553, -3.09447, -3.41867, -3.71761, -4.01445, -4.09655, -4.01445, -3.74287, -3.41867, -3.2292, -2.93237, -2.4987, -1.83556, -1.37452, -0.82085, -0.44191, -0.14297, 0.01913]
y_exp = [9.83e-14, 1.32e-9, 1.69e-8, 1.96e-7, 5.29e-7, 1.30e-6, 2.12e-6, 2.96e-6, 4.10e-6, 5.22e-6, 6.16e-6, 6.16e-6, 6.16e-6, 6.16e-6, 1.43e-8, 5.82e-9, 4.18e-9, 3.02e-9, 2.16e-9, 1.70e-9, 1.32e-9, 9.58e-10, 6.87e-10, 4.57e-10, 3.03e-10, 2.18e-10, 1.22e-10, 6.41e-11, 3.05e-11, 4.40e-10, 2.46e-9, 1.48e-8, 3.11e-8, 8.32e-8, 1.89e-7, 3.65e-7, 7.61e-7, 1.59e-6, 3.34e-6, 5.02e-6, 7.56e-6, 8.21e-6, 9.69e-6, 9.69e-6, 9.69e-6, 6.96e-6, 5.02e-6, 4.26e-6, 3.63e-6, 2.04e-6, 8.98e-7, 3.97e-7, 1.60e-7, 7.09e-8, 3.38e-8, 1.90e-8, 9.89e-9, 5.57e-9]

# Styled to match exactly: dashed red line
plt.semilogy(x_exp, y_exp, 'r--', label="Experimental Data", alpha=0.6, linewidth=1.5)

# =================================================================
# PART 3: Upload and Process Verilog-A Data
# =================================================================
print("Upload your 'verilog_data.txt' (Current:Col 0, Voltage:Col 1)")
uploaded = files.upload()

def parse_spice_safe(val):
    val = str(val).lower().strip()
    m = {'z': 1e-21, 'a': 1e-18, 'f': 1e-15, 'p': 1e-12, 'n': 1e-9, 'u': 1e-6, 'm': 1e-3, 'k': 1e3, 'meg': 1e6}
    try: return float(val)
    except ValueError:
        try: return float(val[:-1]) * m[val[-1]] if val[-1] in m else np.nan
        except: return np.nan

if uploaded:
    fname = list(uploaded.keys())[0]
    df = pd.read_csv(fname, sep=r'\s+', header=0, engine='python')

    # Mapping based on your specific image
    i_raw = df.iloc[:, 0].apply(parse_spice_safe)
    v_raw = df.iloc[:, 1].apply(parse_spice_safe)

    mask = v_raw.notnull() & i_raw.notnull()

    # Using the full array directly since the data is now strictly one cycle
    v_clean = v_raw[mask].values
    i_clean = np.abs(i_raw[mask].values)

    # =================================================================
    # PART 4: Final Plotting & Visualization
    # =================================================================
    plt.semilogy(v_clean, i_clean, color='forestgreen', linestyle='-', label="Verilog-A (Steady-State)", linewidth=2.5)

plt.xlabel("Voltage (V)", fontsize=11)
plt.ylabel("Current (A)", fontsize=11)
plt.title("MoTe2 Phase-Change Memristor Comparison", fontsize=13)

# Place legend exactly in the lower left
plt.legend(loc="lower left", fontsize=10)

# Match grid styling
plt.grid(True, which="major", color='lightgray', alpha=0.6)

plt.tight_layout()
plt.show()